name: Rust build and release

on:
  - push
  - pull_request

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: Build with Docker
      run: |
        docker build -t local/bestbind .
        CID=$(docker create local/bestbind)
        docker cp ${CID}:/bestbind .
        docker cp ${CID}:/libbinder.so .
        docker rm ${CID}

    - name: Build Debian package
      run: |
        cp libbinder.so deb/usr/lib/bestbind/
        cp bestbind deb/usr/bin/
        dpkg-deb --build deb bestbind.deb

    - name: Deploy - Create and Upload Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        artifacts: bestbind libbinder.so bestbind.deb
